import { AuthStore } from "@/stores/auth.store";
import Head from "next/head";
import { useRouter } from "next/router";
import React, { useEffect } from "react";

interface UnauthorizedLayoutProps {
  children: React.ReactNode;
  title: string;
}

const UnauthorizedLayout: React.FC<UnauthorizedLayoutProps> = ({
  children,
  title,
}) => {
  const route = useRouter();
  const token = AuthStore((state) => state.access_token);

  useEffect(() => {
    if (token && route.isReady) route.replace("/product");
  }, [token, route]);

  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {children}
    </>
  );
};

export default UnauthorizedLayout;
